# Generated by Django 4.2.7 on 2023-12-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccountmodel',
            name='birth_day',
            field=models.DateField(null=True),
        ),
    ]
