# Generated by Django 4.2.7 on 2023-12-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userbankaccountmodel_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccountmodel',
            name='is_bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
